"use strict";
exports.ORDER_CHANGE_REQUESTED = "ORDER_CHANGE_REQUESTED";
exports.TEAM_FIXTURE_DISPLAY_REQUESTED = "TEAM_FIXTURE_DISPLAY_REQUESTED";
exports.TABLE_STATUS_CHANGE_REQUESTED = "TABLE_STATUS_CHANGE_REQUESTED";
exports.VIEW_CHANGE_REQUESTED = "VIEW_CHANGE_REQUESTED";
//# sourceMappingURL=tags.js.map