export const ORDER_CHANGE_REQUESTED = "ORDER_CHANGE_REQUESTED";
export const TEAM_FIXTURE_DISPLAY_REQUESTED = "TEAM_FIXTURE_DISPLAY_REQUESTED";
export const TABLE_STATUS_CHANGE_REQUESTED = "TABLE_STATUS_CHANGE_REQUESTED";
export const VIEW_CHANGE_REQUESTED = "VIEW_CHANGE_REQUESTED";
export const RELOAD_REQUESTED = "RELOAD_REQUESTED";